version: "2"

issues:
  exclude-dirs:
    - extension

linters:
  enable:
    - prealloc
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - staticcheck
        text: "SA5011"
      - path: extension/
        linters:
          - govet
